# NUMPY

In [1]:
import numpy as np
a=np.array([10,20,30])    #create array element seprated with space
print(a)                  # create 1d array
print(type(a))

[10 20 30]
<class 'numpy.ndarray'>


In [2]:
x=[10,20,30]       # create list seprated with comma
print(x)

[10, 20, 30]


In [3]:
a=np.array([10,20,30,4.5])
print(a)

[10.  20.  30.   4.5]


In [4]:
a=np.array([10,20,30,4.5,"hi"])
print(a)

['10' '20' '30' '4.5' 'hi']


In [5]:
a=np.array([10,20,30,4.5],dtype=np.int16)
print(a)

[10 20 30  4]


In [6]:
a=np.array([10,20,30,4.5,'hi'],dtype=np.float16)    #string not convert to float
print(a)

ValueError: could not convert string to float: 'hi'

In [106]:
a=np.array([10,20,30,-10],dtype=np.uint8)
print(a)

[ 10  20  30 246]


C:\Users\user\AppData\Local\Temp\ipykernel_8496\1601642664.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -10 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  a=np.array([10,20,30,-10],dtype=np.uint8)


In [107]:
a=np.arange(1,10,2) # arange use to create array we can create array with array func and arange func
print(a)

[1 3 5 7 9]


In [108]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [109]:
a=np.arange(5,10)
print(a)

[5 6 7 8 9]


In [110]:
a=np.arange(1.1,2.5,.1)   # arange can take int/float as a args and return nd array
print(a)

[1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1 2.2 2.3 2.4]


In [7]:
a=np.array([10,20,30,256],dtype=np.uint8)   # uint range only 255 we can give 256 it can be 0 outside of range
print(a) 

[10 20 30  0]


C:\Users\user\AppData\Local\Temp\ipykernel_8496\2317908011.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 256 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  a=np.array([10,20,30,256],dtype=np.uint8)   # uint range only 255 we can give 256 it can be 0 outside of range


In [1]:
a=np.zeros(10)       # 5 is size
print(a)
a[-1]=50   # 50 tells us index position of -1
print(a)

NameError: name 'np' is not defined

In [9]:
a=np.ones(5)       # 5 is size by default it gives float
print(a)

[1. 1. 1. 1. 1.]


In [10]:
a=np.full(5,10) # it takes size and initial value
print(a)

[10 10 10 10 10]


In [11]:
a=np.linspace(5,50,10)     # 5 and 50 both are inclusive  and  10 is size # not give a size it can take default size 50
print(a)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [12]:
a=np.random.randint(1,100,10) # low, high ,size it generate 10 value from 1 to 100 randomly and 100 in exclusive and repeat no.
print(a)

[74 46  5 41 52 38  1 73  2 81]


In [13]:
a=np.random.uniform(1,100,10)  # it gives float no. low ,high ,size
print(a)

[88.54302898 65.25121983 49.72667974 86.00798904 68.26561351 86.2548584
 92.50606322 51.79786772 63.88847797 14.90209115]


In [14]:
x=list(range(20)) #list consume more memory
a=np.arange(20)  #array consume less memory fast compare to list
print(x)
print(a)
import sys    #it help to get memory sixe
print(sys.getsizeof(x))
print(sys.getsizeof(a))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
216
192


In [15]:
# Diff. list and ndarray(numpy array)
# array support  boolean slicing 
# support broadcasting
#similiar type of element
#memory optimization
#support statical operation

#list any type of element
#not support boolean slicing 
#not support broadcasting
#poor support statical operation

In [16]:
a=np.array([[1,2],[3,4],[5,6]])  # create 2d array it is called matrix
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [17]:
#all 2D array is not matrix ,matrix is 2D array , 2D array is jagged array means diff size # matrix same size
#numpy has no jagged array

In [18]:
a=np.array([[1,2],[3,4],[5]])  #1D array numpy no jagged aray
print(a)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [19]:
a=np.zeros((3,4)) # row, colomn
print(a)
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
a=np.ones((3,4))   # row colomn
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
a=np.full((3,4),20)   # (r,c),initial value
print(a)

[[20 20 20 20]
 [20 20 20 20]
 [20 20 20 20]]


In [22]:
a=np.random.randint(1,100,(3,3)) # low, high ,(r,c)
print(a)

[[50 12 45]
 [90 34 93]
 [65 10 32]]


In [23]:
a=np.random.uniform(1,100,(3,3))
print(a)

[[15.63058193 12.11505987 20.51140315]
 [44.16991974  8.19006559 55.37723241]
 [32.60266336 93.48300538 94.39522664]]


In [24]:
a=np.eye(3,3)  # r,c eye means idendity matrix main diagonal is 1 and all is 0
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
a=np.random.randint(1,10,(3,4))   #numpy 2d array
print(a)  

[[7 1 4 4]
 [4 5 9 5]
 [9 7 9 6]]


In [26]:
b=a.reshape(4,3,order='c')#c lang.(row major order reshape) i.e, read and write row wise #store in variable to use in program 

In [27]:
c=a.reshape(4,3,order='f') #fortran lang.(colomn major order reshape) i.e, read and write colomn wise

In [28]:
print(b)

[[7 1 4]
 [4 4 5]
 [9 5 9]
 [7 9 6]]


In [29]:
print(c)

[[7 5 9]
 [4 7 4]
 [9 4 5]
 [1 9 6]]


In [30]:
print(a)

[[7 1 4 4]
 [4 5 9 5]
 [9 7 9 6]]


In [31]:
a.reshape(4,3) # not defined order so default order c 

array([[7, 1, 4],
       [4, 4, 5],
       [9, 5, 9],
       [7, 9, 6]])

In [32]:
a.reshape(2,6)

array([[7, 1, 4, 4, 4, 5],
       [9, 5, 9, 7, 9, 6]])

In [33]:
a.reshape(1,12)

array([[7, 1, 4, 4, 4, 5, 9, 5, 9, 7, 9, 6]])

In [34]:
a.reshape(12,1)

array([[7],
       [1],
       [4],
       [4],
       [4],
       [5],
       [9],
       [5],
       [9],
       [7],
       [9],
       [6]])

In [35]:
a.reshape(4,-1)

array([[7, 1, 4],
       [4, 4, 5],
       [9, 5, 9],
       [7, 9, 6]])

In [36]:
a.reshape(-1,3)  #auto compute through -1 meams knoe only one dimension

array([[7, 1, 4],
       [4, 4, 5],
       [9, 5, 9],
       [7, 9, 6]])

In [37]:
a.reshape(-1,-1)

ValueError: can only specify one unknown dimension

In [38]:
a

array([[7, 1, 4, 4],
       [4, 5, 9, 5],
       [9, 7, 9, 6]])

In [39]:
a.resize(3,6,refcheck=False)#reshape use same size and change dimension value and resize means change size and dimension value

In [40]:
a

array([[7, 1, 4, 4, 4, 5],
       [9, 5, 9, 7, 9, 6],
       [0, 0, 0, 0, 0, 0]])

In [41]:
a.resize(6,3)

In [42]:
a

array([[7, 1, 4],
       [4, 4, 5],
       [9, 5, 9],
       [7, 9, 6],
       [0, 0, 0],
       [0, 0, 0]])

In [43]:
a.resize(3,3,refcheck=False) #to give new size use reference

In [44]:
a

array([[7, 1, 4],
       [4, 4, 5],
       [9, 5, 9]])

In [45]:
b=np.resize(a,(6,4))  
b

array([[7, 1, 4, 4],
       [4, 5, 9, 5],
       [9, 7, 1, 4],
       [4, 4, 5, 9],
       [5, 9, 7, 1],
       [4, 4, 4, 5]])

In [46]:
#diff, a,resizr and np.resiz
#a.size()
#method of array 
#modify existing array
#fill zero if size is changed
#refcheck=false,if we change size

# np.resize()
#function of numpy
#return a copy
#repeat element if size is changed
#not applicable

In [47]:
#diff reshaepe and resize
#reshape
#new size is not possible we can only change dimension
#one -ve dims allow

#resize
#new size is possible along with dims
# not allow


In [48]:
b.reshape(3,2,4)  #  create 3d array using reshape ,2 is row and 4 is colomn (3 is size of 3d array)


array([[[7, 1, 4, 4],
        [4, 5, 9, 5]],

       [[9, 7, 1, 4],
        [4, 4, 5, 9]],

       [[5, 9, 7, 1],
        [4, 4, 4, 5]]])

In [49]:
b.reshape(4,2,3)  # 3d array means array of 2d

array([[[7, 1, 4],
        [4, 4, 5]],

       [[9, 5, 9],
        [7, 1, 4]],

       [[4, 4, 5],
        [9, 5, 9]],

       [[7, 1, 4],
        [4, 4, 5]]])

In [50]:
b.reshape(2,2,3,2) # create 4d array means array of 3d 2 is size of 4d array .2 is size of 3d array

array([[[[7, 1],
         [4, 4],
         [4, 5]],

        [[9, 5],
         [9, 7],
         [1, 4]]],


       [[[4, 4],
         [5, 9],
         [5, 9]],

        [[7, 1],
         [4, 4],
         [4, 5]]]])

In [51]:
b.flatten() #convert  2d, 3d ,4d...array to 1d array use flatten()

array([7, 1, 4, 4, 4, 5, 9, 5, 9, 7, 1, 4, 4, 4, 5, 9, 5, 9, 7, 1, 4, 4,
       4, 5])

In [52]:
b.flatten(order='f') #flatten create new 1d array not modify

array([7, 4, 9, 4, 5, 4, 1, 5, 7, 4, 9, 4, 4, 9, 1, 5, 7, 4, 4, 5, 4, 9,
       1, 5])

In [53]:
b

array([[7, 1, 4, 4],
       [4, 5, 9, 5],
       [9, 7, 1, 4],
       [4, 4, 5, 9],
       [5, 9, 7, 1],
       [4, 4, 4, 5]])

In [54]:
a=np.arange(10) #1 d array
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
a.reshape(2,5)  # use reshape/resize to convert 1d array into 2d, 3d ....

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [56]:
import numpy as np

In [57]:
a=np.random.randint(1,100,10)

In [58]:
print(a)

[31  6 51 52 81 80 84 54 16  7]


In [59]:
b=np.random.randint(1,100,(3,3))
print(b)

[[46 73 53]
 [15 74 87]
 [17 79 72]]


In [60]:
print(a.min()) # return min element from array
print(b.min())  #return min element from array
print(b.min(axis=1)) #return min element from each row of array
print(b.min(axis=0))#return min element from each column of array
print(a.argmin())#return index of min element from  array#return index of min element from  array
print(b.argmin())# first flatten then return index of min element from  array#return index of min element from  array

6
15
[46 15 17]
[15 73 53]
1
3


In [61]:
print(a.max())
print(b.max())
print(b.max(axis=1))
print(b.max(axis=0))
print(a.argmax())
print(a.argmax())

84
87
[73 87 79]
[46 79 87]
6
6


In [62]:
print(a.sum())#return sum of all element present in array
print(b.sum())#return sum of all element present in array
print(b.sum(axis=1))#return sum of all element present in each row from  array
print(b.sum(axis=0))#return sum of all element present in each  colomn from  array

462
516
[172 176 168]
[ 78 226 212]


In [63]:
print(a)

[31  6 51 52 81 80 84 54 16  7]


In [64]:
print(np.where(a==93))# return indexing using where condition is satisfy
print(np.where(a>=24))#np.function,array.method

(array([], dtype=int64),)
(array([0, 2, 3, 4, 5, 6, 7], dtype=int64),)


In [65]:
print(a.sum()) #print sum using array method
print(np.sum(a)) #print sum using numpy function

462
462


In [66]:
print(a.mean()) #mean
print(np.mean(a))

46.2
46.2


In [67]:
print(a.std())  #standard deviation
print(np.median(a)) #median

28.62795836241208
51.5


# Broadcasting

In [68]:
a

array([31,  6, 51, 52, 81, 80, 84, 54, 16,  7])

In [69]:
print(a+1) #return new array after pointing   broadcasting arthematic

[32  7 52 53 82 81 85 55 17  8]


In [70]:
x=[10,12,30] #list has no broadcasting
print(x+1)

TypeError: can only concatenate list (not "int") to list

In [71]:
y=[]  #through list add 1 element using for loop
for i in x:
    y.append(i+1)
print(y)

[11, 13, 31]


In [72]:
b=np.sqrt(a) #return new array after computing sqrt of each element in array
print(b)

[5.56776436 2.44948974 7.14142843 7.21110255 9.         8.94427191
 9.16515139 7.34846923 4.         2.64575131]


In [73]:
np.round(b,2) #return new array after doing broadcast round of 2 decimal place

array([5.57, 2.45, 7.14, 7.21, 9.  , 8.94, 9.17, 7.35, 4.  , 2.65])

In [74]:
np.log(a) #base e

array([3.4339872 , 1.79175947, 3.93182563, 3.95124372, 4.39444915,
       4.38202663, 4.4308168 , 3.98898405, 2.77258872, 1.94591015])

In [75]:
np.log10(a)

array([1.49136169, 0.77815125, 1.70757018, 1.71600334, 1.90848502,
       1.90308999, 1.92427929, 1.73239376, 1.20411998, 0.84509804])

In [76]:
np.log2(a)

array([4.95419631, 2.5849625 , 5.67242534, 5.70043972, 6.33985   ,
       6.32192809, 6.39231742, 5.7548875 , 4.        , 2.80735492])

In [77]:
m=np.array([56,65,76,76,46]) #find avg. marks
c=np.array([67,89,38,66,59])
p=np.array([66,77,88,55,99])
print(m+c+p)
print(np.round((m+c+p)/3,2))

[189 231 202 197 204]
[63.   77.   67.33 65.67 68.  ]


In [78]:
x=np.array([56,65,67,76,46])  #check the which  poisition has  same array with where condition
y=np.array([56,89,38,76,46])
print(np.where(x==y))
print(np.where(x!=y))
print(np.where(x>y))
        

(array([0, 3, 4], dtype=int64),)
(array([1, 2], dtype=int64),)
(array([2], dtype=int64),)


In [79]:
x=[20000,15000,60000,45000,25000]
for i in x:
    if(i>30000):
        print(i)


60000
45000


In [80]:
a=np.array(x)
print(a)
#x[start:stop:end]
#array[condition]

[20000 15000 60000 45000 25000]


In [81]:
a[a>30000] #conditional slicing in array

array([60000, 45000])

In [82]:
a=np.random.randint(1,100,10)
print(a)

[40 66 42 46 42 42 71 49 27 78]


In [83]:
a[(a>50) | (a%2==0)]# boolean and conditional slicing use more statement  usebitwise operator use to combine


array([40, 66, 42, 46, 42, 42, 71, 78])

In [84]:
a[(a>50) & (a%2==0)]

array([66, 78])

In [85]:
m=np.random.randint(1,10,(3,3))
print(m)

[[2 7 8]
 [2 1 3]
 [4 8 7]]


In [86]:
m.transpose()    # transpose means rows convert colomn and colomn convert row

array([[2, 2, 4],
       [7, 1, 8],
       [8, 3, 7]])

In [87]:
m.T  # T means transpose

array([[2, 2, 4],
       [7, 1, 8],
       [8, 3, 7]])

In [88]:
m

array([[2, 7, 8],
       [2, 1, 3],
       [4, 8, 7]])

In [89]:
m*2 #  multiply by 2 each no. give new matrix existing not change

array([[ 4, 14, 16],
       [ 4,  2,  6],
       [ 8, 16, 14]])

In [90]:
n=m.T
print(m)

[[2 7 8]
 [2 1 3]
 [4 8 7]]


In [91]:
print(n)

[[2 2 4]
 [7 1 8]
 [8 3 7]]


In [92]:
m*n # element by element multiply

array([[ 4, 14, 32],
       [14,  1, 24],
       [32, 24, 49]])

In [93]:
np.dot(m,n)  #dot product of two matrix using dot function

array([[117,  35, 120],
       [ 35,  14,  37],
       [120,  37, 129]])

In [94]:
m@n   # another way  to find dot product using @ operator

array([[117,  35, 120],
       [ 35,  14,  37],
       [120,  37, 129]])

In [95]:
a

array([40, 66, 42, 46, 42, 42, 71, 49, 27, 78])

In [96]:
a[0]=100 #replace the value of index poistion

In [97]:
print(a)

[100  66  42  46  42  42  71  49  27  78]


In [98]:
a[a>50]=200 #replace 50 greater value with 200

In [99]:
a

array([200, 200,  42,  46,  42,  42, 200,  49,  27, 200])

In [100]:
del a[0] #replace array element but not delete

ValueError: cannot delete array elements

In [101]:
np.delete(a,0) #gives new array

array([200,  42,  46,  42,  42, 200,  49,  27, 200])

In [102]:
m

array([[2, 7, 8],
       [2, 1, 3],
       [4, 8, 7]])

In [103]:
np.delete(m,0) # first flatten the matrix and del array from gives index poisition and gives flaten array

array([7, 8, 2, 1, 3, 4, 8, 7])

In [104]:
m

array([[2, 7, 8],
       [2, 1, 3],
       [4, 8, 7]])

In [105]:
m[m%2==0] #conditional slicing on matrix gives flaten array 

array([2, 8, 2, 4, 8])